name: dap
description: Dart SDK for Decentralized Agnostic Paytags (DAPs).
version: 0.1.0
repository: https://github.com/TBD54566975/dap-dart

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  http: ^1.2.0
  typeid: ^1.0.1
  web5: ^0.2.0


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
